module.exports =
{
    'userSignUp': '/api/user-signUp',
    'userLogin': '/api/user-login',
    'merchantSignUp': '/api/merchant-signUp',
    'merchantLogin': '/api/merchant-login',
    'passwordReset': '/api/passwordReset',
    'mobileRecharge': '/api/mobileRecharge',
    'dstvRecharge': '/api/dstv',
    'gotv':'/api/gotv',
    'electricityRecharge': '/api/eltricBills',
    'getAllcreditCards':'/api/creditCards',
    'getAllUsers':'/api/users',
    'getAllMerchants':'/api/merchants',
    'updateMerchant' : '/api/update/merchant/:id',
    'updateUser' : '/api/update/user/:id',
    'getCurrentMerchant':'/api/current/merchant/:id',
    'deleteUser':'/api/delete/user/:id',
    'deleteMerchant':'/api/delete/merchant/:id',
    'getCurrentUser':'/api/current/user/:id',
    'getSingleMerchant': '/api/merchant/:id',
    'getSingleUser': '/api/user/:id',
    'getSingleCreditCards': '/api/creditCards/:id',
}